// swift-tools-version:6.2
import PackageDescription

let package = Package(
    name: "AuroraDrive",
    platforms: [.macOS(.v26)],
    targets: [
        // MetalGoose (GPL v3.0, upstream unmodified) — 仅用于显示路径超分/插帧
        // MGFG-1 插帧需要 macOS 26+ 的 MetalFX；本 target 以 Swift 6 模式编译。
        .target(
            name: "MetalGooseEngine",
            path: "Vendor/MetalGoose/Engine",
            resources: [.copy("Shaders.metal")]
        ),
        .executableTarget(
            name: "AuroraDrive",
            dependencies: ["MetalGooseEngine"],
            path: ".",
            // 源码在 src/AuroraDrive/；其余子目录是运行时用磁盘路径读取的数据/研究/备份文档，
            // 并非 target 内容。显式排除，避免 SwiftPM 将它们视为"未声明文件"告警。
            exclude: [
                ".build",
                ".trae",
                ".workbuddy",
                "AuroraDrive日志备份",
                "档案留存",
                "上一版的失败代码",
                "研究索引",
                "Apollo研究",
                "BEVFormer研究",
                "NVIDIA研究",
                "OpenPilot研究",
                "ROS2生态研究",
                "UniAD研究",
                "纯规则研究",
                "backups",
                "configs",
                "data",
                "diag_area",
                "diag_steps",
                "docs",
                "models",
                "scripts",
                "src",
                "tools",
                "Vendor",
                ".vscode",
                ".venv-yolo26",
                "AuroraDrive.app",
                "__pycache__",
                "checkpoints",
                "recordings",
                "2026-08-18.md",
                "7x24隐藏bug清单_20260816.md",
                "AuroraDriveUI",
                "AuroraDriveUI.bak-0017",
                "AuroraDriveUI.bak-212619",
                "docs/LICENSE",
                "docs/NOTICE",
                "docs/README.md",
                "docs/QUICKSTART.md",
                "docs/ARCHITECTURE.md",
                "app_ui_clone.html",
                "automation_preview.html",
                "color_live_031607.png",
                "diag_area.py",
                "diag_aspect.py",
                "diag_leaves.py",
                "diag_steps.py",
                "diag_white.py",
                "diag_white2.py",
                "diag_white_only.png",
                "exp_iso.py",
                "fuse.py",
                "gen_0817_033439.png",
                "gen_0817_033439b.png",
                "gen_120743.png",
                "gen_220338.png",
                "geom_0817_curve.png",
                "geom_0817_iso.png",
                "geom_0817_pts.png",
                "icon.icns",
                "lane_annotator.html",
                "lane_batches.json",
                "lane_cv2_v9.py",
                "lane_fused.png",
                "lane_geom_B_curve.png",
                "lane_geom_B_edges.png",
                "lane_geom_B_iso.png",
                "lane_geom_B_live_031551.png",
                "lane_geom_B_out.png",
                "lane_geom_B_pts.png",
                "lane_geom_sourceB.py",
                "lane_merge.py",
                "lane_points_only.png",
                "lane_verify.py",
                "manual_lane_000760.py",
                "pointcloud_debug.png",
                "pointcloud_debug.py",
                "pre_color.png",
                "pre_color.py",
                "pre_color2.png",
                "pre_color2.py",
                "pre_color3.png",
                "pre_color3.py",
                "pre_color4.png",
                "pre_color4.py",
                "pre_color5.png",
                "pre_color5.py",
                "pre_combo.png",
                "pre_combo.py",
                "pre_combo2.png",
                "pre_combo2.py",
                "pre_gray.png",
                "pre_gray.py",
                "pre_hsv.png",
                "pre_hsv.py",
                "pre_sky.py",
                "pre_step1.png",
                "pre_step1.py",
                "pre_step2_try.py",
                "pre_try.png",
                "pre_try10.png",
                "pre_try10.py",
                "pre_try2.png",
                "pre_try2.py",
                "pre_try3.png",
                "pre_try3.py",
                "pre_try4.png",
                "pre_try4.py",
                "pre_try5.png",
                "pre_try5.py",
                "pre_try6.png",
                "pre_try6.py",
                "pre_try7.png",
                "pre_try7.py",
                "pre_try8.png",
                "pre_try8.py",
                "pre_try9.png",
                "pre_try9.py",
                "pre_v3.py",
                "sourceC.py",
                "sourceC_demo.png",
                "train.log",
                "ui_preview_keyboard.jpg",
                "v94_blob_dropped.png",
                "v94_boosted.png",
                "v94_color_points.png",
                "v94_color_points_blue.png",
                "v94_diag.py",
                "v94_on_boosted.png",
                "v94_on_combo2.png",
                "v94_points.py",
                "v94_points_blue.py",
                "v94_pre.py",
                "v94_redpoints.png",
                "v94_verify_dash.py",
                "v94_verify_dash2.py",
                "v94_verify_shadow.py",
                "yolo26s.pt",
                "延迟审计报告_20260815.md",
                "深度代码评审报告_20260816.md",
                "深度理解_AuroraDrive_2026-08-09.md",
                "补丁扫描清单_20260816.md",
            ],
            sources: [
                "src/AuroraDrive/AuroraDriveApp.swift",
                "src/AuroraDrive/AutomationPanel.swift",
                "src/AuroraDrive/CaptureEngine.swift",
                "src/AuroraDrive/ConfidenceEstimator.swift",
                "src/AuroraDrive/ControlEngine.swift",
                "src/AuroraDrive/DegradeStateMachine.swift",
                "src/AuroraDrive/EscapeController.swift",
                "src/AuroraDrive/GameMapView.swift",
                "src/AuroraDrive/InferenceEngine.swift",
                "src/AuroraDrive/KeyboardMonitor.swift",
                "src/AuroraDrive/MinimapLocatorView.swift",
                "src/AuroraDrive/RecordEngine.swift",
                "src/AuroraDrive/RuleController.swift",
                "src/AuroraDrive/SpeedOCRReader.swift",
                "src/AuroraDrive/VisualLocator.swift",
                "src/AuroraDrive/YoloEngine.swift"
            ],
            swiftSettings: [
                // 主程序保持 Swift 5 语言模式，避免严格并发模式破坏既有并发代码
                .swiftLanguageMode(.v5)
            ]
        )
    ]
)
